@baseUrl = http://localhost:5100
@categoryId =08de6f12-7c92-bd9b-00d8-61bd5a580000
@courseId =08de6cd5-a690-75ac-00d8-61bd5a580000
@userId =898688f4-de46-415f-a393-9e73b8fb3bd1

# Get Categories
GET {{baseUrl}}/api/v1.0/categories
Accept: application/json

###

# Create Category
POST {{baseUrl}}/api/v1.0/categories
Accept: application/json
Content-Type: application/json

{
  "categoryName": "Test"
}
###
GET {{baseUrl}}/api/v1.0/categories/{{categoryId}}
Accept: application/json
###
POST {{baseUrl}}/api/v1.0/course
Accept: application/json
Content-Type: application/json
{
  "name": "Test Course",
  "description": "This is a test course.",
  "imageUrl": "http://example.com/image.jpg",
  "price": 99.99,
  "categoryId": "{{categoryId}}"
}
###
PUT {{baseUrl}}/api/v1.0/course
Accept: application/json
Content-Type: application/json
{
  "Id":"{{courseId}}",
  "name": "Test Course33",
  "description": "This is a test course33.",
  "imageUrl": "http://example.com/image2.jpg",
  "price": 199.99,
  "categoryId": "{{categoryId}}"
}
###
GET {{baseUrl}}/api/v1.0/course
Accept: application/json
###
GET {{baseUrl}}/api/v1.0/course/{{courseId}}
Accept: application/json

###
Delete {{baseUrl}}/api/v1.0/course/{{courseId}}
Accept: application/json

###
# Get Courses by UserId
GET {{baseUrl}}/api/v1.0/course/user/{{userId}}
Accept: application/json