@baseUrl = http://localhost:5174
@productId1 = 08de6cd5-a690-75ac-00d8-61bd5a580001
@productId2 = 08de6cd5-a690-75ac-00d8-61bd5a580002

### Create Order
POST {{baseUrl}}/api/v1.0/orders
Accept: application/json
Content-Type: application/json

{
  "discount":50,
  "address": {
    "province": "Istanbul",
    "city": "Kadikoy",
    "region": "Marmara",
    "street": "Caferaga Mahallesi, Moda Caddesi No:123",
    "postalCode": "34710"
  },
  "payment": {
    "cardName": "John Doe",
    "cardNumber": "4532015112830366",
    "expiration": "12/25",
    "cvv": "123",
    "amount": 5000
  },
  "orders": [
    {
      "productId": "{{productId1}}",
      "productName": "Product0",
      "unitPrice": 200
    },
    {
      "productId": "{{productId2}}",
      "productName": "Product7",
      "unitPrice": 300
    }
  ]
}

###

### Get Orders
GET {{baseUrl}}/api/v1.0/orders
Accept: application/json

###
